config/routes.rb
Rails.application.routes.draw do
  get '/scores'  , to: 'scores#index'               # global high scores
  root 'chem_pages#home'                            # main page
  get '/quiz', to: 'quizzes#show'                   # current quiz for user or redirects to choose quiz if none
  patch '/quiz', to: 'quizzes#update'               # answers questions on a quiz
  get '/quiz_view/:id', to: 'quizzes#view',         # show selected quiz - admin
                        as: :quiz_view
  get '/help', to: 'chem_pages#help'                # help page
  get '/about', to: 'chem_pages#about'              # about page
  get '/contact', to: 'chem_pages#contact'          # contact page
  get  '/signup',  to: 'users#new'                  # sign up form for new users
  post '/signup',  to: 'users#create'               # posts to users to create new user then redirects to user page
  get '/profile', to: 'users#profile'               # shows current user profile
  get    '/login',   to: 'sessions#new'             # login page
  post   '/login',   to: 'sessions#create'          # logs in
  delete '/logout',  to: 'sessions#destroy'         # logs out
  resources :users, only: [ :index,                 # index page of all users - admin
                            :show,                  # shows a user - admin
                            :edit,                  # form to edit current user
                            :update,                # post to update current user
                            :destroy ]              # deletes user - admin
  resources :quizzes, only: [ :index ]              # index of quizzes - admin
  resources :questions, only: [ :index,             # shows all questions - admin
                                :show ]             # shows a question - admin
  resources :account_activations, only: [ :edit ]   # link to activate account
  resources :password_resets,     only: [ :new,     # form for password reset
                                          :create,  # send password reset email
                                          :edit,    # form to change password after reset
                                          :update ] # change password after reset
  resources :quiz_types,          only: [ :index,   # choose quiz page
                                          :show ]   # creates chosen quiz and redirects to quiz page
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
  has_many :answers, :dependent => :destroy
  has_one :quiz_type, through: :quiz
  has_one :user, through: :quiz
  
  validates :prompt,  presence: true
  validates :correct_answer,  presence: true
  validates :quiz_id,  presence: true
  validates :answered,  inclusion: [true, false]
  
  def answer_question(answer)
    if !self.answered
      self.update(answered: true, chosen_answer: answer)
      Quiz.increment_counter(:score, self.quiz.id) if self.chosen_answer == self.correct_answer
    end
  end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :admin_user,     only: [:index, :show]
  
  def index
    @questions = Question.paginate(page: params[:page], per_page: 20)
  end
  
  def show
    @question = Question.find(params[:id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/index.html.erb
<% provide(:title, "Question Index") %>
<h1>Questions</h1>

<%= will_paginate %>
<table>
  <tr>
    <th>ID</th>
    <th>Quiz Type</th>
    <th>Quiz ID</th>
    <th>Prompt</th>
    <th></th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.quiz.quiz_type.name %></td>
      <td><%= question.quiz.id %></td>
      <td><%= question.prompt %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate %>

app/views/questions/show.html.erb
<% provide(:title, "Question #{@question.id}") %>

<p>
  <span id="question_info">Question ID:</span> <%= @question.id %>
</p>
<p>
  <span id="question_info">Quiz ID:</span> <%= @question.quiz_id %>
</p>
<p>
  <span id="question_info">Prompt:</span> <%= @question.prompt %>
</p>
<p>
  <span id="question_info">Answers:</span>
</p>

<ul class="answer">
  <% @question.answers.each do |answer| %>
    <li><%= answer.text %></li>
  <% end %>
</ul>

<p>
  <span id="question_info">Correct Answer:</span> <%= @question.correct_answer %>
</p>
<p>
  <span id="question_info">Answered:</span> <%= @question.answered %>
</p>
<p>
  <span id="question_info">Chosen Answer:</span> <%= @question.chosen_answer %>
</p>
<p>
  <span id="question_info">Created:</span> <%= @question.created_at %>
</p>
<p>
  <span id="question_info">Updated:</span> <%= @question.updated_at %>
</p>

<%= link_to "Back", questions_path %>