config/routes.rb
Rails.application.routes.draw do
  get '/scores'  , to: 'scores#index'               # global high scores
  root 'chem_pages#home'                            # main page
  get '/quiz', to: 'quizzes#show'                   # current quiz for user or redirects to choose quiz if none
  patch '/quiz', to: 'quizzes#update'               # answers questions on a quiz
  get '/quiz_view/:id', to: 'quizzes#view',         # show selected quiz - admin
                        as: :quiz_view
  get '/help', to: 'chem_pages#help'                # help page
  get '/about', to: 'chem_pages#about'              # about page
  get '/contact', to: 'chem_pages#contact'          # contact page
  get  '/signup',  to: 'users#new'                  # sign up form for new users
  post '/signup',  to: 'users#create'               # posts to users to create new user then redirects to user page
  get '/profile', to: 'users#profile'               # shows current user profile
  get    '/login',   to: 'sessions#new'             # login page
  post   '/login',   to: 'sessions#create'          # logs in
  delete '/logout',  to: 'sessions#destroy'         # logs out
  resources :users, only: [ :index,                 # index page of all users - admin
                            :show,                  # shows a user - admin
                            :edit,                  # form to edit current user
                            :update,                # post to update current user
                            :destroy ]              # deletes user - admin
  resources :quizzes, only: [ :index ]              # index of quizzes - admin
  resources :questions, only: [ :index,             # shows all questions - admin
                                :show ]             # shows a question - admin
  resources :account_activations, only: [ :edit ]   # link to activate account
  resources :password_resets,     only: [ :new,     # form for password reset
                                          :create,  # send password reset email
                                          :edit,    # form to change password after reset
                                          :update ] # change password after reset
  resources :quiz_types,          only: [ :index,   # choose quiz page
                                          :show ]   # creates chosen quiz and redirects to quiz page
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  
  has_many :scores, :dependent => :destroy
  has_one :quiz, :dependent => :destroy
  
  before_save   :downcase_email
  before_create :create_activation_digest
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  
  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      email.downcase!
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :profile]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy, :show]

  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @scores = @user.scores.sort_by {|score| [score.quiz_type.name, score.quiz_type.level] }
  end
  
  def profile
    @user = current_user
    @scores = @user.scores.sort_by {|score| [score.quiz_type.name, score.quiz_type.level] }
    render 'show'
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_time(time)
    return "-" if !time
    hours = time >= 3600 ? "#{time / 3600}h " : ""
    minutes = time >= 60 ? "#{(time % 3600) / 60}m " : ""
    seconds = "#{time % 60}s"
    return "#{hours}#{minutes}#{seconds}"
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= "\u{2B50}" %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Delete User: Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, user_path) %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-2">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  <%= link_to "Choose a new quiz", quiz_types_path, class: "btn btn-lg btn-primary" %>
  </aside>
  

  <div class="col-md-10">
    <table class="scoretable">
      <tr>
        <th>Quiz</th>
        <th>Level</th>
        <th>Difficulty</th>
        <th>Your Highest Score</th>
        <th>Fastest Time For 100% Correct</th>
      </tr>
  
      <% @scores.each do |score| %>
        <tr class="scores">
          <td class="col1"><%= link_to score.quiz_type.name, quiz_type_path(score.quiz_type_id) %></td>
          <td class="col2"><%= score.quiz_type.level %></td>
          <td class="col2"><%= score.quiz_type.difficulty %></td>
          <td class="col3"><%= "#{score.score} / #{score.quiz_type.num_questions}" %></td>
          <td class="col3"><%= format_time(score.fastest_time) %></td>
        </tr>
      <% end %>
    </table>
  </div>

</div>