config/routes.rb
Rails.application.routes.draw do
  get '/scores'  , to: 'scores#index'               # global high scores
  root 'chem_pages#home'                            # main page
  get '/quiz', to: 'quizzes#show'                   # current quiz for user or redirects to choose quiz if none
  patch '/quiz', to: 'quizzes#update'               # answers questions on a quiz
  get '/quiz_view/:id', to: 'quizzes#view',         # show selected quiz - admin
                        as: :quiz_view
  get '/help', to: 'chem_pages#help'                # help page
  get '/about', to: 'chem_pages#about'              # about page
  get '/contact', to: 'chem_pages#contact'          # contact page
  get  '/signup',  to: 'users#new'                  # sign up form for new users
  post '/signup',  to: 'users#create'               # posts to users to create new user then redirects to user page
  get '/profile', to: 'users#profile'               # shows current user profile
  get    '/login',   to: 'sessions#new'             # login page
  post   '/login',   to: 'sessions#create'          # logs in
  delete '/logout',  to: 'sessions#destroy'         # logs out
  resources :users, only: [ :index,                 # index page of all users - admin
                            :show,                  # shows a user - admin
                            :edit,                  # form to edit current user
                            :update,                # post to update current user
                            :destroy ]              # deletes user - admin
  resources :quizzes, only: [ :index ]              # index of quizzes - admin
  resources :questions, only: [ :index,             # shows all questions - admin
                                :show ]             # shows a question - admin
  resources :account_activations, only: [ :edit ]   # link to activate account
  resources :password_resets,     only: [ :new,     # form for password reset
                                          :create,  # send password reset email
                                          :edit,    # form to change password after reset
                                          :update ] # change password after reset
  resources :quiz_types,          only: [ :index,   # choose quiz page
                                          :show ]   # creates chosen quiz and redirects to quiz page
end

app/controllers/chem_pages_controller.rb
class ChemPagesController < ApplicationController
  
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/chem_pages_helper.rb
module ChemPagesHelper
end

app/views/chem_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Chemistry Quiz</h1>
<p>Chemistry Quiz helps you practice your chemistry skills by taking quizzes.</p>

app/views/chem_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Chemistry Quiz
  <%= mail_to "chemistryquiz@example.co.uk", "here" %>
</p>

app/views/chem_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help for Chemistry Quiz</h1>
<p>Choose a quiz and see how well you can do.  Quizzes have different levels with increasing difficulty.</p>
<p>Create an account and go to your profile to see your high scores.</p>

app/views/chem_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center jumbotron">
  <div class="home-image">
    <%= image_tag('lab.jpg') %>
  </div>
  
  <h1 class="maintitle">Chemistry Quiz</h1>
  
  <%= link_to "High Scores", scores_path, class: "btn btn-lg btn-primary home" %>
  <% if logged_in? %>
  
    <%= link_to "Start a new quiz", quiz_types_path, class: "btn btn-lg btn-primary home" %>
    <%= link_to "Resume quiz", quiz_path, class: "btn btn-lg btn-primary home" %>
  <% else %>
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary home" %>
  <% end %>
</div>