config/routes.rb
Rails.application.routes.draw do
  get '/scores'  , to: 'scores#index'               # global high scores
  root 'chem_pages#home'                            # main page
  get '/quiz', to: 'quizzes#show'                   # current quiz for user or redirects to choose quiz if none
  patch '/quiz', to: 'quizzes#update'               # answers questions on a quiz
  get '/quiz_view/:id', to: 'quizzes#view',         # show selected quiz - admin
                        as: :quiz_view
  get '/help', to: 'chem_pages#help'                # help page
  get '/about', to: 'chem_pages#about'              # about page
  get '/contact', to: 'chem_pages#contact'          # contact page
  get  '/signup',  to: 'users#new'                  # sign up form for new users
  post '/signup',  to: 'users#create'               # posts to users to create new user then redirects to user page
  get '/profile', to: 'users#profile'               # shows current user profile
  get    '/login',   to: 'sessions#new'             # login page
  post   '/login',   to: 'sessions#create'          # logs in
  delete '/logout',  to: 'sessions#destroy'         # logs out
  resources :users, only: [ :index,                 # index page of all users - admin
                            :show,                  # shows a user - admin
                            :edit,                  # form to edit current user
                            :update,                # post to update current user
                            :destroy ]              # deletes user - admin
  resources :quizzes, only: [ :index ]              # index of quizzes - admin
  resources :questions, only: [ :index,             # shows all questions - admin
                                :show ]             # shows a question - admin
  resources :account_activations, only: [ :edit ]   # link to activate account
  resources :password_resets,     only: [ :new,     # form for password reset
                                          :create,  # send password reset email
                                          :edit,    # form to change password after reset
                                          :update ] # change password after reset
  resources :quiz_types,          only: [ :index,   # choose quiz page
                                          :show ]   # creates chosen quiz and redirects to quiz page
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Chemistry Quiz", root_path %>
    by David Morton
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "chemistry quiz", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "High Scores", scores_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Admin <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Quizzes", quizzes_path %></li>
                <li><%= link_to "Questions", questions_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>